<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Features\Handlers\Flight\QueryHandlers\" />
      <Folder Include="Features\Queries\Flight\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\SkySync.Services.Flight.Domain\SkySync.Services.Flight.Domain.csproj" />
      <ProjectReference Include="..\..\..\..\Infrastructure\SkySync.Shared\SkySync.Shared.csproj" />
    </ItemGroup>

</Project>
