<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-SkySync.Workers.Outbox-332d6d51-45b2-4567-be63-4a3d10c3df8a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MassTransit" Version="8.5.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.15.0-beta.1" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />
        <PackageReference Include="MassTransit.EntityFrameworkCore" Version="8.5.0" />
        <PackageReference Include="MassTransit.Newtonsoft" Version="8.5.0" />
        <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Services\Flight\Infrastructure\SkySync.Services.Flight.Persistence\SkySync.Services.Flight.Persistence.csproj" />
        <ProjectReference Include="..\..\Services\Reservation\Infrastructure\SkySync.Services.Reservation.Persistence\SkySync.Services.Reservation.Persistence.csproj" />
        <ProjectReference Include="..\..\Infrastructure\SkySync.Shared\SkySync.Shared.csproj" />
    </ItemGroup>
</Project>
